### ISSUE TITLE
Integrate Firebase into project

### ISSUE THREAD

**Issue by somenath1435** [NJACKWinterOfCode/TranslateX#1]
Add Firebase into app

**Comment by Ashish0077** [comment]
what firebase services need to be integrated?
- Realtime database
- Firebase Storage
?
please provide more detail @somenath1435

**Comment by somenath1435** [comment]
@Ashish0077 intergrate this https://firebase.google.com/docs/ml-kit/android/translate-text

**Comment by Ashish0077** [comment]
very basic initial implementation @somenath1435 

![Screenshot_1575288078](https://user-images.githubusercontent.com/12756600/69957921-b7388b00-1529-11ea-86e2-24bd69191907.png)
![Screenshot_1575288101](https://user-images.githubusercontent.com/12756600/69957929-bbfd3f00-1529-11ea-81c8-5e206ab1f3b5.png)
![Screenshot_1575288118](https://user-images.githubusercontent.com/12756600/69957938-c0295c80-1529-11ea-9651-e630a4364c67.png)

**Comment by somenath1435** [comment]
@Ashish0077 give permission to somenath1435@gmail.com in firebase console

**Comment by Ashish0077** [comment]
@somenath1435  done

**Comment by somenath1435** [comment]
@Ashish0077 
After solving a problem in pull request write "fix #issue_name"
