### ISSUE TITLE
Improve Current UI

### ISSUE THREAD

**Issue by somenath1435** [NJACKWinterOfCode/TranslateX#3]
**Describe the solution you'd like**
Make home screen similar to google translate

**Additional context**
This issue only deals with frontend part

**Comment by pavitrawalia** [comment]
@somenath1435 Can I take up this issue?

**Comment by somenath1435** [comment]
@pavitrawalia wait till I merge the pending pull requests... Stay tuned

**Comment by somenath1435** [comment]
@pavitrawalia Now you can. Make sure to attach screenshots

**Comment by pavitrawalia** [comment]
@somenath1435  I have created a pull request .
