### ISSUE TITLE
Implement Language Translation for all languages

### ISSUE THREAD

**Issue by somenath1435** [NJACKWinterOfCode/TranslateX#5]
**Is your feature request related to a problem? Please describe.**
Currently, app can translate to only german

**Describe the solution you'd like**
Use other api functionality

**Comment by Ashish0077** [comment]
reference : https://firebase.google.com/docs/ml-kit/translation-language-support
we can translate to 59 languages
i would like to add a spinner via which user can select language to whichever they want to translate and then download the specific language model and translate
@somenath1435

**Comment by somenath1435** [comment]
@Ashish0077 Go ahead

**Comment by MahmoudMabrok** [comment]
if it completed please close it.
