### ISSUE TITLE
Add a CI Tool ex: CircleCI, TravisCI

### ISSUE THREAD

**Issue by Ashish0077** [NJACKWinterOfCode/TranslateX#7]
**What is CI?**
 Continuous integration (CI) is the practice of automating the integration of code changes from multiple contributors into a single software project.

**Comment by Ashish0077** [comment]
I would like to work on Integrating Circle CI on this project

**Comment by ShivangiSingh17** [comment]
@Ashish0077 go ahead.

**Comment by refactor-droidyy** [comment]
@ShivangiSingh17 can I work on this issue if not assigned to someone?

**Comment by ShivangiSingh17** [comment]
@Ashish0077 are you working on this issue?

**Comment by Ashish0077** [comment]
@ShivangiSingh17 busy with exams
@refactor-droidyy you can work on this

**Comment by s-ayush2903** [comment]
@somenath1435 can I sove it if no-one else is willing to do so?
And also please add some label(level_of_difficulty) to it
