### ISSUE TITLE
Log-in and Sign-up Activities 

### ISSUE THREAD

**Issue by Sarthak2601** [NJACKWinterOfCode/TranslateX#9]
Integrate Firebase. 
Implement Sign Up Activity
Implement Log in Activity 
Implement Google Sign in 
Implement Facebook Sign in

**Comment by Sarthak2601** [comment]
Working on it.

**Comment by somenath1435** [comment]
@Sarthak2601 close all issue regarding signin and signup and only create one issue regarding both signin and signup....

**Comment by Sarthak2601** [comment]
> @Sarthak2601 close all issue regarding signin and signup and only create one issue regarding both signin and signup....

Done..

**Comment by VARUN12KUMAR** [comment]
can i work on this issue??

**Comment by Sarthak2601** [comment]
@VARUN12KUMAR Already working on it brother.
